version: '3'

volumes:
  kittygram_pg_data:
  static_kittygram:
  media_kittygram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
  backend:
    image: arseniyyanes/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/app/backend_static
      - media_kittygram:/media
  frontend:
    env_file: .env
    image: arseniyyanes/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/static
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: arseniyyanes/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_kittygram:/static/
      - media_kittygram:/media
